# Coverage configuration
# ----------------------
coverage:
  status:
    patch: true

  range: 50..100     # First number represents red, and second represents green
  # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - mridc/launch.py
  - mridc/core/classes/loss.py
  - mridc/core/classes/export.py
  - mridc/core/classes/module.py
  - mridc/core/conf/dataloader.py
  - mridc/core/conf/base_config.py
  - mridc/core/conf/hydra_runner.py
  - mridc/core/optim/optimizer_with_master_params.py
  - mridc/collections/common/data/*
  - mridc/collections/common/metrics/*
  - mridc/collections/common/callbacks/*
  - mridc/collections/common/parts/patch_utils.py
  - mridc/collections/common/parts/ptl_overrides.py
  - mridc/collections/common/parts/training_utils.py
  - mridc/collections/common/losses/aggregator.py
  - mridc/collections/reconstruction/models/pics.py
  - mridc/collections/reconstruction/models/zf.py
  - mridc/core/utils/*
  - mridc/utils/arguments.py
  - mridc/utils/debug_hook.py
  - mridc/utils/distributed.py
  - mridc/utils/export_utils.py
  - mridc/utils/decorators/*
  - projects/*
  - projects/quantitative/datasets/ahead/*
  - setup.py

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
comment:
  layout: diff, files  # accepted in any order: reach, diff, flags, and/or files
