pretrained: false
checkpoint: None
mode: train

model:
  model_name: DECOCIRIM
  recurrent_layer: IndRNN
  conv_filters:
    - 64
    - 64
    - 2
  conv_kernels:
    - 5
    - 3
    - 3
  conv_dilations:
    - 1
    - 2
    - 1
  conv_bias:
    - true
    - true
    - false
  recurrent_filters:
    - 64
    - 64
    - 0
  recurrent_kernels:
    - 1
    - 1
    - 0
  recurrent_dilations:
    - 1
    - 1
    - 0
  recurrent_bias:
    - true
    - true
    - false
  depth: 2
  time_steps: 8
  conv_dim: 2
  num_cascades: 1
  no_dc: true
  keep_eta: true
  coil_combination_method: SENSE
  dimensionality: 2
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  train_loss_fn: l1
  eval_loss_fn: l1
  accumulate_estimates: true
  fft_centered: false
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  random_motion: true
  moco_stn_chans: 32
  moco_stn_num_pools: 2
  moco_stn_in_chans: 4
  moco_stn_out_chans: 4
  moco_stn_drop_prob: 0.0
  moco_stn_padding_size: 15
  moco_stn_normalize: true
  moco_stn_bidirectional: true
  moco_stn_conv_dim: 2
  moco_stn_int_downsize: 2
  moco_stn_int_steps: 7
  moco_stn_input_shape:
    - 190
    - 190
  moco_stn_mode: bilinear
  moco_stn_optimize_registration: true
  moco_clip_value: 0
  moco_lambda_registration: 1e-10
  moco_similarity_loss_win_size: 11
  moco_gradient_loss_penalty: l2
  moco_gradient_loss_reg: 1e-10
  moco_gradient_loss_dimensionality: 2
  moco_lambda_registration_mse: 0
  moco_loss_consenus_coefficient: 1e-10

  train_ds:
    data_path: /data/projects/recon/data/private/3T_T1_3D_Brains/h5/multicoil_train/
    challenge: multicoil
    coil_combination_method: SENSE
    dimensionality: 2
    consecutive_slices: 1
    fft_centered: false
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    random_motion: true
    random_motion_type: gaussian
    random_motion_angle: 30
    random_motion_translation: 30
    random_motion_center_percentage: 0.2
    random_motion_motion_percentage:
      - 80
      - 80
    random_motion_num_segments: 24
    random_motion_random_num_segments: false
    random_motion_non_uniform: false
    random_motion_states_discrepancy_factor: 0.2
    simulate_motion: true
    simulate_motion_translation:
      - 0
      - 0
    simulate_motion_rotation:
      - 0
      - 0
    simulate_motion_scale: 0
    simulate_motion_p: 1966
    simulate_motion_theta: 10
    simulate_motion_sigma: 18
    mask_args:
      type: poisson2d
      accelerations:
        - 6
        - 8
      center_fractions:
        - 0.7
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: true
    normalize_inputs: true
    crop_size:
      - 190
      - 190
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: true
    num_workers: 8
    drop_last: false
    pin_memory: false

  validation_ds:
    data_path: /data/projects/recon/data/private/3T_T1_3D_Brains/h5/multicoil_val/
    challenge: multicoil
    coil_combination_method: SENSE
    dimensionality: 2
    consecutive_slices: 1
    fft_centered: false
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    random_motion: true
    random_motion_type: gaussian
    random_motion_angle: 30
    random_motion_translation: 30
    random_motion_center_percentage: 0.2
    random_motion_motion_percentage:
      - 80
      - 80
    random_motion_num_segments: 24
    random_motion_random_num_segments: false
    random_motion_non_uniform: false
    random_motion_states_discrepancy_factor: 0.2
    simulate_motion: true
    simulate_motion_translation:
      - 0
      - 0
    simulate_motion_rotation:
      - 0
      - 0
    simulate_motion_scale: 0
    simulate_motion_p: 1966
    simulate_motion_theta: 10
    simulate_motion_sigma: 18
    mask_args:
      type: poisson2d
      accelerations:
        - 6
        - 8
      center_fractions:
        - 0.7
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: false
    normalize_inputs: true
    crop_size:
      - 190
      - 190
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 1e-4
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /data/projects/recon/other/dkarkalousos/moco/trained_models/cirim/
  create_tensorboard_logger: false
  create_wandb_logger: true
  wandb_logger_kwargs:
    project: MoCo
  files_to_copy: [ ]
