pretrained: false
checkpoint: ???
mode: test

model:
  model_name: ZF
  coil_combination_method: SENSE
  dimensionality: 2
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 1

  test_ds:
    data_path: /data/projects/recon/data/public/qdess/v1-release/test_normed
    challenge: multicoil
    coil_combination_method: SENSE
    dimensionality: 2
    consecutive_slices: 1
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    random_motion: false
#    motion_degrees: 2
#    motion_translation: 5
#    motion_num_transforms: 1
#    motion_image_interpolation: linear
    mask_args:
      type: poisson2d
      accelerations:
      - 10
      center_fractions:
      - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: false
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: /data/projects/recon/other/dkarkalousos/projects/smk-tea/reconstructions/zf/
  create_tensorboard_logger: true
  files_to_copy: [ ]
